document.writeln("  <!--头部 start-->");
document.writeln("  <div class=\"header fn-clear\">");
document.writeln("    <div class=\"logo fn-left\"> <a href=\"#\" class=\"logo\" title=\"\"> </a> </div>");
document.writeln("    <!--导航条 start-->");
document.writeln("    <div class=\"nav fn-clear\">");
document.writeln("      <ul class=\"fn-clear\">");
document.writeln("        <li> <a href=\"#\" class=\"home\">首页</a> </li>");
document.writeln("        <li> <a href=\"#\" class=\"guide\">攻略</a> </li>");
document.writeln("        <li> <a href=\"#\" class=\"exhibition\">影展</a> </li>");
document.writeln("        <li> <a href=\"#\" class=\"story\">旅行故事</a> </li>");
document.writeln("        <li> <a href=\"#\" class=\"market\"> 跳骚市 </a> </li>");
document.writeln("        <li> <a href=\"#\" class=\"sofa\">换沙发</a> </li>");
document.writeln("        <li> <a href=\"#\" class=\"companion\">找旅伴</a> </li>");
document.writeln("        <li> <a href=\"#\" class=\"insurance\">旅行保险</a> </li>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("    <!--导航条 start--> ");
document.writeln("    <a href=\"#\" class=\"morediv fn-left\"> <span class=\"more fn-left\"> </span> <span class=\"d-black-arrow\"> </span> </a>");
document.writeln("    <div class=\"toolbtn fn-right\"> <div class=\"login-top\"><a href=\"#\" class=\"login\"> 登录 </a><div class=\"login-box\">");
document.writeln("    <p>登录方式</p>");
document.writeln("    <a href=\"#\" class=\"qq\"></a><a href=\"#\" class=\"weibo\"></a><a href=\"#\" class=\"weixin\"></a><a href=\"#\" class=\"douban\"></a><a href=\"#\" class=\"renren\"></a><a href=\"#\" class=\"t\"></a><a href=\"#\" class=\"f\"></a>");
document.writeln("    </div></div> <a href=\"#\" class=\"register\"> 注册 </a><div class=\"en-box\"><a class=\"en\" href=\"#\"> EN <span class=\"d-blue-arrow\"> </span> </a></div> </div>");
document.writeln("  </div>");
document.writeln("  <!--头部 end -->");
document.writeln("");